<!-- Thread Template -->
<script type="text/template" id="thread_template">
    <p><strong><%= name %></strong>&nbsp;<i>(<%= formatDate %>)</i></p>
    <p style="padding-left:15px"><%= message %></p>

    <a style="padding-left:15px;" class="collapsed" data-toggle="collapse" data-parent="#forum_container" href="#section_<%= id %>" data-url="#<%= page %>/thread/<%= id %>">Replay</a>
    <% if(disable_delete){ %>
    <a href="#<%= page %>" id="delete_btn"><i class="glyphicon glyphicon-remove"></i></a>
    <% } %>
    <div id="section_<%= id %>" class="panel panel-collapse collapse">
        <?php
        $form->setAttribute('id', 'forum_replies');
        $form->setAttribute('style', 'font-size:10px');
        $form->get('message')->setAttribute('style', 'height:29px;font-size:.9em;');
        $form->get('submit')->setAttribute('style', 'height:29px;font-size:.9em;');
        ?>
        <div id="reply_form" style="height:.8em">
            <?= $this->form()->openTag($form); ?>
            <?= $this->formInput($form->get('name')); ?>
            <?= $this->formInput($form->get('user_id')); ?>
            <?= $this->formInput($form->get('username')); ?>
            <div class="form-group">
                <div class="col-md-4 col-md-offset-1">
                    <?= $this->formInput($form->get('message')); ?>
                </div>
                <div class="col-md-1" style="padding-left:0px">
                    <?= $this->formInput($form->get('submit')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
        <br></br>
        <div style="margin-left:20px; color:gray" id="replies"></div>

        <div id="reply_paginator_view" class="col-md-12" style="font-size: .7em">
            <ul class="pagination"></ul>
        </div>
    </div>
</script>

<!-- Replies Template -->
<script type="text/template" id="replies_template">
    <p>
        <strong><%= name %></strong>&nbsp;<i>(<%= formatDate %>)</i>
        <% if(disable_delete) { %>
        <a href="#<%= page %>/thread/<%= forum_id %>/<%= thread_page %>" data-id="<%= id %>" id="delete_replies"><i class="glyphicon glyphicon-remove" style="left:2px;top:2px;"></i></a>
        <% } %>
    </p>
    <p style="padding-left:15px"><%= message %></p>
</script>

<!-- Paginator Template -->
<script type="text/template" id="paginator_template">
    <% if(previous && enable_previous){ %>
    <li>
        <a href="#<%= start %>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    <% } %>

    <li <%= is_active %> ><a href="#<%= page %>"><%= page %></a></li>

    <% if(next && enable_next) { %>
    <li>
        <a href="#<%= end %>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    <% } %>
</script>

<!-- Paginator Replies Template -->
<script type="text/template" id="paginator_replies_template">
    <% if(previous && enable_previous){ %>
    <li>
        <a href="#<%= page %>/thread/<%= thread_id %>/<%= start %>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    <% } %>

    <li <%= is_active %> ><a href="#<%= page %>/thread/<%= thread_id %>/<%= id %>"><%= id %></a></li>

    <% if(next && enable_next) { %>
    <li>
        <a href="#<%= page %>/thread/<%= thread_id %>/<%= end %>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    <% } %>
</script>