<!-- Thread Template -->
<script type="text/template" id="thread_template">
    <p><strong><%= name %></strong><span class="posted_date"> posted at <i><%= formatDate %></i></span></p>
    <p class="padding_l15"><%= message %></p>

    <a class="collapsed padding_l15" data-toggle="collapse" data-parent="#forum_container" href="#section_<%= id %>" data-url="#<%= page %>/thread/<%= id %>">Replay</a>
    <% if(disable_delete){ %>
    <a href="#<%= page %>" id="delete_btn"><i class="glyphicon glyphicon-remove"></i></a>
    <% } %>
    <div id="section_<%= id %>" class="panel panel-collapse collapse">
        <?php
        $form->setAttribute('id', 'forum_replies');
        ?>
        <div id="reply_form" style="height:.8em">
            <?= $this->form()->openTag($form); ?>
            <?= $this->formInput($form->get('name')); ?>
            <?= $this->formInput($form->get('user_id')); ?>
            <?= $this->formInput($form->get('username')); ?>
            <div class="form-group">
                    <?= $this->formInput($form->get('message')); ?>
            </div>
             <?= $this->formInput($form->get('submit')); ?>
            <?= $this->form()->closeTag(); ?>
            
        </div>
         <div class="clear-fix"></div>
        <div id="replies"></div>

        <div id="reply_paginator_view" class="col-md-12" style="font-size: .7em">
            <ul class="pagination"></ul>
        </div>
    </div>
</script>

<!-- Replies Template -->
<script type="text/template" id="replies_template">
    <p>
        <strong><%= name %></strong><span class="posted_date"> posted at <i><%= formatDate %></i></span>
        <% if(disable_delete) { %>
        <a href="#<%= page %>/thread/<%= forum_id %>/<%= thread_page %>" data-id="<%= id %>" id="delete_replies"><i class="glyphicon glyphicon-remove" style="left:2px;top:2px;"></i></a>
        <% } %>
    </p>
    <p class="reply_message"><%= message %></p>
</script>

<!-- Paginator Template -->
<script type="text/template" id="paginator_template">
    <% if(previous && enable_previous){ %>
    <li>
        <a href="#<%= start %>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    <% } %>

    <li <%= is_active %> ><a href="#<%= page %>"><%= page %></a></li>

    <% if(next && enable_next) { %>
    <li>
        <a href="#<%= end %>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    <% } %>
</script>

<!-- Paginator Replies Template -->
<script type="text/template" id="paginator_replies_template">
    <% if(previous && enable_previous){ %>
    <li>
        <a href="#<%= page %>/thread/<%= thread_id %>/<%= start %>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    <% } %>

    <li <%= is_active %> ><a href="#<%= page %>/thread/<%= thread_id %>/<%= id %>"><%= id %></a></li>

    <% if(next && enable_next) { %>
    <li>
        <a href="#<%= page %>/thread/<%= thread_id %>/<%= end %>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    <% } %>
</script>