<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CalendarScheduler\Module'                                 => __DIR__ . '/Module.php',
    'CalendarScheduler\Controller\CalendarSchedulerController' => __DIR__ . '/src/CalendarScheduler/Controller/CalendarSchedulerController.php',
);
