<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/<?php echo $breadCrumb[0]; ?>" class="nav-brand" style="padding-right:10px;"><img src="<?php echo $this->basePath(); ?>/samples/order-entry/img/logo.png" height="50px;"  /></a>
        </div>
        <div>
            <ul class="nav navbar-nav" id="navbar-collapse">
                <li class="<?php if($page == 'customer') echo 'active'; ?>"><a href="<?= $this->url('order-entry'); ?>">Customers</a></li>
                <li class="<?php if($page == 'product') echo 'active'; ?>"><a href="<?= $this->url('order-entry', array('action' => 'product')); ?>">Products</a></li>
                <li class="<?php if($page == 'profile') echo 'active'; ?>"><a href="<?= $this->url('order-entry', array('action' => 'profile')); ?>">Profiles</a></li>
            </ul>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li class="<?php if ($page == 'payment-by-name' || $page == 'payment-by-date') echo 'active'; ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Payments <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('order-entry', array('action' => 'payment-by-date')); ?>">Order by date</a></li>
                        <li><a href="<?= $this->url('order-entry', array('action' => 'payment-by-name')); ?>">Group by customers</a></li>
                </li>
            </ul>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li class="<?php if ($page == 'purchase-by-name' || $page == 'purchase-by-date') echo 'active'; ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Purchases <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('order-entry', array('action' => 'purchase-by-date')); ?>">Order by date</a></li>
                        <li><a href="<?= $this->url('order-entry', array('action' => 'purchase-by-name')); ?>">Group by customers</a></li>
                </li>
            </ul>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li class="<?php if ($page == 'add-customer' || $page == 'add-product' || $page == 'add-order') echo 'active'; ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('order-entry', array('action' => 'add-customer')); ?>">Customer</a></li>
                        <li><a href="<?= $this->url('order-entry', array('action' => 'add-product')); ?>">Product</a></li>
                        <li><a href="<?= $this->url('order-entry', array('action' => 'add-order')); ?>">Order Entry</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="form-group">
            <form class="navbar-form navbar-right" role="search"  >
                <div class="col-sm-10" style="padding:0px;">
                    <input type="text" class="form-control" id="search_box" placeholder="Search..."  />
                </div>
            </form>
        </div>
    </div>
</nav>