<script>
    $(function(){
        // search input
        $('#search_box').keyup(function(){
            var this_text = $(this).val();
            this_text = this_text.toLowerCase();
            var target = $('#accordion > div');
		
            $.each(target,function(k,v){
                var obj = $(v);
                var target_text = $(v).find('h4').text();
                target_text = target_text.toLowerCase();

                if(target_text.indexOf(this_text) != -1){
                    obj.removeClass('hide');
                }else{
                    obj.addClass('hide');
                }
            });
        });
	
        // enable/disable input type for full payment
        $('#payment_check').click(function(){
            var is_checked = $('#payment_check:checked').length ? true : false;
            $('#payment_amount').attr('disabled', is_checked);
        });


        $('#payment_btn').click(function(){
            var total_amount = helper.format_decimal($('#payment_check').val());
            var amount_to_pay = $('#payment_check:checked').length ? total_amount : $('#payment_amount').val();
            amount_to_pay = helper.format_decimal(amount_to_pay);
            var balance = helper.format_decimal($('#cust_balance').text());
            var paid_amount = helper.format_decimal($('#paid_amount').text());
            var cust_id = $('#cust_id').val();
            var purchase_id = $('#purchase_id').val();	
            var is_add = true;	
            var err = ['Please check you payment'];
            var no_error = true;

            if(isNaN(amount_to_pay)){
                helper.check_error(err);
                return false;
            }
            if(amount_to_pay == 0 || amount_to_pay < 0){
                helper.check_error(err);
                return false;
            }

            if(paid_amount == 0){
                amount_to_pay = amount_to_pay > total_amount ? total_amount : amount_to_pay;
                var status = (amount_to_pay >= total_amount) ? 1 : 2;
            }else{		
                var status = (amount_to_pay >= balance) ? 1 : 2;
                amount_to_pay = amount_to_pay > balance ? total_amount : amount_to_pay + paid_amount;
                is_add = false;	
            }
            

            if(amount_to_pay){
                // add payment table
                if(is_add){	
                    var data = {cust_id:cust_id, purchase_id:purchase_id, amount:amount_to_pay};
                    var add_payment_result = api.addPayment(data);
                    if(add_payment_result.response == 200){
                        var data = {status:status};
                        var update_purchase_result = api.updatePurchase(purchase_id,data);
                        if(update_purchase_result.response != 200) {
                            no_error = false;
                        }
                    }else{
                        no_error = false;
                    }
                // update payment table
                }else{
                    var payment_id = $('#payment_id').val();
                    var data = {amount:amount_to_pay};
                    var update_payment_result = api.updatePayment(payment_id, data);
                    if(update_payment_result.response == 200){
                        var data = {status:status};
                        var update_purchase_result = api.updatePurchase(purchase_id, data);
                        if(update_purchase_result.response != 200){
                            no_error = false;
                        }
                    }else{
                        no_error = false;
                    }
                }
                
                if(no_error){
                    helper.success_msg('Payment successfully updated');
                }else{
                    helper.check_error(['Internal error.']);
                }
                
            }
        });

        // close call back upon successfully updated
        $('#modal-close-callsback').click(function(){
            var cust_id = $('#cust_id').val();
            window.location = api.site_url + '/profile/'+cust_id;
        });

    });
</script>
<div class="container">
    <div class="page-header">
        <?php
        if ($id) {
            ?>
            <h2>Payment <small></small></h2>
            <?php
        } else {
            ?>
            <h2>Purchase <small>Group by customers</small></h2>
            <?php
        }
        ?>
    </div>
    <?php
    if ($id) {
        if ($customerPurchase) {
            ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <span class="panel-title"><?php echo $customerPurchase->first_name . " " . $customerPurchase->last_name; ?></span>
                        </div>
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>	
                                        <th>Amount paid</th>
                                        <th>Balance</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $total = $this->format_decimal($customerPurchase->price * $customerPurchase->quantity);
                                    $paid = $this->format_decimal($customerPurchase->amount);
                                    $balance = $this->format_decimal($customerPurchase->balance);
                                    ?>
                                    <tr>
                                        <td><?= $customerPurchase->product; ?></td>
                                        <td><?= $customerPurchase->price; ?></td>
                                        <td><?= $customerPurchase->quantity; ?></td>
                                        <td><?= $total; ?></td>
                                        <td id='paid_amount'><?= $paid; ?></td>
                                        <td id='cust_balance'><?= $balance; ?></td>
                                    </tr>
                                    <?php
                                    ?>
                                </tbody>
                            </table>
                            <?php
                            if ($balance != "0.00") {
                                ?>
                                <form class="form form-inline" role="form">
                                    <div class="form-group">
                                        <label class="sr-only" for="first_name">Amount</label>
                                        <input type="text" placeholder="Enter amount" id="payment_amount" disabled class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="checkbox-inline"><input id="payment_check" checked="true" type="checkbox" value="<?php echo $total; ?>">Full payment</label>
                                    </div>
                                    <div class="form-group">
                                        <input type="button" id="payment_btn" value="Submit" class="form-control btn btn-primary" />
                                        <input type="hidden" id="cust_id" value="<?php echo $customerPurchase->cust_id; ?>"/>
                                        <input type="hidden" id="purchase_id" value="<?php echo $customerPurchase->id; ?>"/>
                                        <input type="hidden" id="payment_id" value="<?php echo $customerPurchase->payment_id; ?>"/>
                                    </div>
                            </div>
                            </form>
                            <?php
                        }
                    } else {
                        ?>
                        No data
                        <?php
                    }
                    ?>

                </div>
            </div>
        </div>
    </div>

    <?php
} else {
    if ($customersPurchases) {
        ?>
        <div id='accordion' class='panel-group'>
            <?php
            foreach ($customersPurchases as $val) {
                ?>
                <div class='panel panel-success'>
                    <div class='panel-heading'>
                        <h4>
                            <a href='#section<?= $val->id; ?>' data-parent='#accordion' data-toggle='collapse' class='collapsed'>
                                <?= $val->first_name . " " . $val->last_name ?>
                            </a>
                        </h4>
                    </div>
                    <div class='panel-collapse collapse' id='section<?= $val->id ?>'>
                        <div class='panel-body'>
                            <?php
                            ?>
                            <table class="table table-condensed ">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity</th>	
                                        <th>Total</th>
                                        <th>Balance</th>
                                        <th >Date</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <?php
                                if (count($val->purchases)) {
                                    ?>
                                    <tbody>
                                        <?php
                                        $total_balance = 0;
                                        foreach ($val->purchases as $key => $val) {
                                            $key++;
                                            $total = $this->format_decimal($val->quantity * $val->price);
                                            $paid_amount = $this->format_decimal($val->paid_amount);
                                            $balance = $this->format_decimal($total - $paid_amount);
                                            $total_balance += $balance;
                                            $color = array('danger', 'success', 'warning');
                                            $paynow = ($val->status != 1) ? "<a class='btn btn-primary' href='" . $this->url('order-entry', array('action' => 'customer-payment', 'id' => $val->id)) . "'>Pay Now</a>" : "<span class='btn disabled'>Paid</span>";
                                            ?>
                                            <tr class='<?= $color[$val->status]; ?>'>
                                                <td><?= $key; ?></td>
                                                <td><?= $val->product; ?></td>
                                                <td><?= $val->price; ?></td>
                                                <td><?= $val->quantity; ?></td>								
                                                <td><?= $total; ?></td>
                                                <td><?= $balance; ?></td>
                                                <td><?= $val->date; ?></td>
                                                <td><?= $paynow; ?></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                    </tbody>
                                    <tfoot style='padding:0px'>
                                        <tr>
                                            <td colspan='6' align='right'>Total Balance</td>
                                            <td colspan='2'><?= $total_balance ?></td>
                                        </tr>
                                    </tfoot>
                                    <?php
                                } else {
                                    ?>
                                    <tbody><tr><td colspan='8' align='center'>No transaction's yet</td></tr></tbody>
                                    <?php
                                }
                                ?>
                            </table>
                            <?php
                            ?>

                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
        </div> <!-- end panel-group -->
        <?php
    } else {
        ?>
        <h3>No records yet</h3>
        <?php
    }
}
?>
</div> <!-- end container -->