<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AnimalQuiz\Module'                          => __DIR__ . '/Module.php',
    'AnimalQuiz\Controller\AnimalQuizController' => __DIR__ . '/src/AnimalQuiz/Controller/AnimalQuizController.php',
    'AnimalQuiz\Model\Animals'                   => __DIR__ . '/src/AnimalQuiz/Model/Animals.php',
);
