<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Baguio Tours</title>
        <script type="text/javascript" src="<?= $this->basePath('js/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/jquery.slidertron-0.1.js'); ?>"></script>
        <link href="<?php echo $this->basePath('samples/web-designs/design-one/style.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
        <style type="text/css">
            @import "<?php echo $this->basePath('samples/web-designs/design-one/slidertron.css'); ?>";
        </style>
    </head>
    <?php echo $this->content; ?>
    </html>