<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>AMS Jewelry Collection</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="pain d o" content="" />
        <script type="text/javascript" src="<?= $this->basePath('js/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('samples/web-designs/design-five/basic_calendar.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/prototype.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/scriptaculous.js?load=effects,builder'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/lightbox.js'); ?>"></script>
        <link href="<?php echo $this->basePath('css/lightbox.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?php echo $this->basePath('samples/web-designs/design-five/css/style.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <?php echo $this->content; ?>
</html>