<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>N63 Enterprise</title>
        <link href="<?php echo $this->basePath('samples/web-designs/design-four/css/style.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="<?= $this->basePath('js/prototype.js'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/scriptaculous.js?load=effects,builder'); ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/lightbox.js'); ?>"></script>
        <link href="<?php echo $this->basePath('css/lightbox.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <?php echo $this->content; ?>
</html>