<?php
$form = $this->form;
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $this->formLabel($form->get('event')); ?>
    <div class="col-sm-10">
        <?= $this->formInput($form->get('event')); ?>
    </div>
</div>
<div class="form_to float_left">
    <div class="form-group">
        <?= $this->formLabel($form->get('from')); ?>
        <div class="col-sm-8 bootstrap-timepicker padding_left_10 form_to_responsive">
            <?= $this->formInput($form->get('from')); ?>
        </div> 
    </div>
</div>
<div class="form_to float_left">
    <div class="form-group">
        <?= $this->formLabel($form->get('to')); ?>
        <div class="col-sm-9 bootstrap-timepicker padding_left_0 form_to_responsive">
            <?= $this->formInput($form->get('to')); ?>
        </div>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('location')); ?>
    <div class="col-sm-10">
        <?= $this->formInput($form->get('location')); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->formButton($form->get('btn_add')); ?>
        <?= $this->formButton($form->get('btn_update')); ?>
        <?= $this->formButton($form->get('btn_delete')); ?>
        <?= $this->formButton($form->get('btn_cancel')); ?>
    </div>
</div>
<?= $this->formhidden($form->get('hidden_id')); ?>
<?= $this->formhidden($form->get('hidden_selected_date')); ?>
<?= $this->form()->closeTag(); ?>