
<div class="container">
    <h4 style="text-align:center">Simple Calendar Scheduler</h4>
    <div class="row">
        <div class="well" style="padding:5px; width:400px;margin:auto">
            <button class="btn-warning date_navi" id="left_navi" style="width:10%;display:inline-block"><i class="glyphicon glyphicon-arrow-left"></i></button>
            <div style="width:75%;display:inline-block;text-align:center" id="month_title"></div>
            <button class="btn-warning date_navi" id="right_navi"  style="width:10%;display:inline-block"><i class="glyphicon glyphicon-arrow-right"></i></button>
            <hr />
            <div id="holder"></div>
        </div>
    </div>
    <input type="hidden" id="hidden_month"/>
    <input type="hidden" id="hidden_year"/>
</div>
<div aria-hidden="false" role="dialog" tabindex="-1" id="calendarModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="padding-top:5px;padding-bottom:5px;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>Simple Calendar Scheduler</h4>
            </div>
            <div class="modal-body">

                <?= $this->render('CALENDAR_SCHEDULER_FORM',array('form' => $form)); ?>

                <table id="calendar_table" class="table table-striped table-condensed table-hover">
                    <colgroup>
                        <col width="10%" />
                        <col width="30%" />
                        <col width="35%" />
                        <col width="25%" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Event</th>
                            <th>Time</th>
                            <th>location</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-primary" type="button">Close</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="base_url" value="<?= $this->url('calendar-scheduler'); ?>/" />