<?php
$form = $this->form;
$form->prepare();
if (count($successMsg)) {
    foreach ($successMsg as $message) {
        echo '<p><b class="text-success">' . $message . '</b></p>';
    }
}
if ($errMsg) {
    echo '<p><b class="text-danger">' . $errMsg . '</b></p>';
}
?>
<h2>Login Form</h2>
<div class="container">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
    <a href="<?= $this->url('backbone-js-blog-register-login', array('action' => 'register')); ?>">You don't have an account yet?</a>
</div>
