<?php
$form = $this->form;
$form->setAttribute('action', $this->url('backbone-js-blog-register-login', array('action' => 'register')));
$form->prepare();
?>


<div class="container">
    <h2>Register</h2>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formHidden($form->get('security')); ?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-md-4">
            <?php echo $this->formInput($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('username')); ?>
        <div class="col-md-4">
            <?php echo $this->formInput($form->get('username')); ?>
            <?php echo $this->formElementErrors($form->get('username')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('password')); ?>
        <div class="col-md-4">
            <?php echo $this->formPassword($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('confirm_password')); ?>
        <div class="col-md-4">
            <?php echo $this->formPassword($form->get('confirm_password')); ?>
            <?php echo $this->formElementErrors($form->get('confirm_password')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('submit')); ?>
        <div class="col-md-4">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
     <div class="form-group">
        <label for="submit" class="control-label sr-only col-md-2">csrf</label>
        <div class="col-md-4"><?php echo $this->formElementErrors($form->get('security')); ?></div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>