<div id="main_con">
<div id="form_con">
	<form role="form" class="form-horizontal">
	<div class="col-md-8 search_con">
	<input type="input" id="search" placeholder="search video" class="form-control" />
	</div>
	<div class="col-md-2 btn_con">
	<button id="search_btn" class="btn btn-default btn_background">search</button>
	</div>
	</form>
</div>
<div class="clear-fix"></div>

<div id="show_header">Simple Youtube Mini Search</div>
<div id="result">
<img src="<?= $this->basePath('samples/widgets/youtube/img/youtube_logo.jpg'); ?>" width="308px"/>
</div>
<div id="show_footer"></div>
</div>