<body>
    <?php $mylogo_url = $this->basePath('samples/web-designs/images/mylogo.jpg'); ?>

    <div id="wrapper">
        <div id="bar">
            <img src="<?php echo $this->basePath('samples/web-designs/design-four/images/logo.png'); ?>" />
            <ul>
                <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Home</a></li>
                <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Products</a></li>
                <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>About</a></li>
                <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Contact Us</a></li>
            </ul>
        </div>
        <div id="pin">
            <img src="<?php echo $this->basePath('samples/web-designs/design-four/images/pin.gif'); ?>" />  
        </div>
        <div class="clear"></div>

        <div id="row1">
            <div id="col1">
                <h2>Categories</h2>
                <select name="status" value="" >
                    <option value="">Select Category</option>
                    <option value="">Hardware</option>
                    <option value="">Software</option>
                    <option value="">Database</option>
                    <option value="">Server</option>
                    <option value="">Storage</option>
                    <option value="">Printer</option>
                    <option value="">Computer</option>
                    <option value="">Laptop</option>
                </select>

                <input type="submit" value="Go" />
                <h2>Popular Programs</h2>
                <select name="status" value="" >
                    <option value="">Select Category</option>
                    <option value="">Javascript</option>
                    <option value="">PHP</option>
                    <option value="">C#</option>
                    <option value="">.Net</option>
                    <option value="">CGI</option>
                    <option value="">Perl</option>
                    <option value="">Visual Studio</option>
                    <option value="">Python</option>
                </select>

                <input type="submit" value="Go" />
                <h2>Archives</h2>
                <ul>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>January 2011</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>December 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>November 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>October 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>September 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>August 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>July 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>June 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>May 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>April 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>March 2010</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>February 2010</a></li>
                </ul>
                <h2>Suppliers</h2>
                <ul style="height:428px;">
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>PC Express</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>PC Madness</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Laptop On The Go</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Enigma</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>PC For Me</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Mac Gadgets</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>GBX Inc.</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Solar System PC</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>PCX Inc.</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Nautica Gadgets</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Cellphone PC</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Battle Computer</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Games Softwares</a></li>
                    <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Computer Inc.</a></li>
                </ul>
            </div><!-- end col1 div -->

            <div id="col2">
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Advanced SystemCare Free</a></h2>
                <p>Advanced SystemCare Free is a comprehensive PC care utility that takes an one-click approach to help protect, repair and optimize your computer. Finding what other utilities miss, it can keep your PC error-free and smooth than ever.</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>RecordMax Burning Studio 4.6.8</a></h2>
                <p>Many users are tired of over-complicated CD burning applications that are getting harder and harder to use. Sometimes you can waste most of your time just trying to find a function. RecordMax Burning Studio focuses on what you want!</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>VentaFax 6.6.133.340</a></h2>
                <p>You can send and receive black and white or color faxes after scaling through the configuration hurdle. You can also retrieve your fax and voice messages from any touchtone phone, and enjoy email and fax forwarding directly as attachment. One other feature that makes it a program worth trying out is its ability to record a telephone conversation with just a single click. Moreover, VentaFax 6.6.133.340 also supports Caller ID (if available)</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>MicroOLAP Database Designer for PostgreSQL 1.3.2</a></h2>
                <p>With MicroOLAP Database Designer for PostgreSQL, you can create a ready-to-use PostgreSQL database with a few clicks; while keeping its structure up-to-date by synchronizing it with the changes already made by you to a visual diagram. The program has the ability to generate complex data in safe; and this is beside the fact that you can synchronize several databases to the state of your diagram.</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>QManga 0.3</a></h2>
                <p>QManga is an image viewing program designed to read images sequentially as is the case with Manga. All common image formats are supported and images can also be loaded from within zips and rars without extraction. QManga also supports Nested zips, right to left reading mode, and Unicode support also enhance the reading of manga. The user-interface is very easy to understand compared to CDisplay. QManga 0.3 requires Microsoft Visual C++ 2008 redistributable before installation can be made. Some of its latest changes include: support for cbz and cbr; some window geometry bug fixes; faster reload speed; addition of scroll sensitivity options; addition of rotation options; and addition of don't enlarge images option. However, this version does not have support for color separation. As a matter of fact, not many changes were made to this version.</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Export Query to Text for SQL Server 1.06.42</a></h2>
                <p>Export Query for Microsoft SQL Server helps to save a query results to text file. The program supports delimited or fixed length formats. Export utility has easy to learn and to use wizard interface. All modern versions of SQL Server are supported.</p>
                <h2><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>File Uneraser 1.26.6</a></h2>
                <p>RaidLabs File Uneraser unerases files which were deleted, including documents, pictures, mp3 and zip files, folders and even damaged disks. The program scans a target drive absolutely automatically and selects the right solution for file unerase.</p>
            </div><!-- end col2 div -->

        </div><!-- end row1 div -->
        <div class="clear"></div>

        <div id="footer">
            <span>Copyright &copy; N63 Enterprise. All Rights Reserved  | DESIGN BY MOLI S.</span>
        </div>	 
    </div><!-- end wrapper div -->


</body>