<body>
    <?php $mylogo_url = $this->basePath('samples/web-designs/images/mylogo.jpg'); ?>

   <div id="navi_holder">
    <div id="navi">
    	<div>
        <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Home</a></li>
        </ul>
        </div>
        <div>
        <ul>
        	 <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Admin</a></li>
        </ul>
        </div>
    </div>
</div>
<div id="head_holder">
	<div id="head">
        <div id="head_text">
        AMS Jewelry Collection
        </div>
	</div>
</div>

<div id="content_holder">
	<div id="content">

	<div id="right">
		<div id="search">
		<div>Google Search</div>
	   <form action="http://www.google.com/search" method="get" target="_blank">
	   <div id="text"><input type="text" name="q" /></div>
	   <div id="btn"><button style="margin-left: -8px;"><img src="images/search_icon.png" border="0" /></button></div>
	   </form>
	  
		</div>

		<div id="calendar">
		<script type="text/javascript">
		var todaydate=new Date()
		var curmonth=todaydate.getMonth()+1 //get current month (1-12)
		var curyear=todaydate.getFullYear() //get current year
		document.write(buildCal(curmonth ,curyear, "main", "month", "daysofweek", "days", 1));
		</script> 
		</div>      
	</div><!-- end right -->




	<div class="products">
	
	<div id="prod" style="width: 600px; background-color: #fff;">
		<div style="width: 150px; float: left;"><br /><br /><br />
		<a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'><img src='<?= $this->basePath('samples/web-designs/design-five/images/thumb_1.jpg'); ?>' border='0' id='image_hover' /></a> 		<!--image-->
		</div>
		
		<div style="width: 449px; float: right; border-left: 1px solid #ccc; font-size: .8em;">
			<div style="background: #ddd; padding: 5px;">
			<span>Neckless with pendant keys</span><br />																		<!--title-->	
			<span style='color: #999; font-size: .7em; font-style: italic; padding-bottom: 5px;'>March 14, 2011</span>
			</div>
			<div style="padding: 5px;">																							<!--description-->
			From left to right:
			first:<br />
			While gold, LV neckless with diamonds planted on LV pendant, worth 120k PHP.<br />
			Second:<br />
			White gold neckless and yellow gold channel pendant, worth 50k PHP.<br />
			Third:<br />
			Yellow gold channel neckless, worth 50k PHP.<br />
			Fourth:<br />
			Yellow gold neckless with custom made key pendant, planted with 4 diamond, worth 70k PHP.<br /><br />

			Note: Prices will be change base on USD currency.
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="prod" style="width: 600px; background-color: #fff;">
		<div style="width: 150px; float: left;">
		<a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'><img src='<?= $this->basePath('samples/web-designs/design-five/images/thumb_3.jpg'); ?>' border='0' id='image_hover' /></a> 		<!--image-->
		</div>
		
		<div style="width: 449px; float: right; border-left: 1px solid #ccc; font-size: .8em;">
			<div style="background: #ddd; padding: 5px;">
			<span>Tri-coloured neckless set</span><br />																		<!--title-->	
			<span style='color: #999; font-size: .7em; font-style: italic; padding-bottom: 5px;'>Macrh 18, 2011</span>
			</div>
			<div style="padding: 5px;">																							<!--description-->
			This Tri-colored neckless set with custom seven white gold pendant, planted with diamond on each.<br />
			Current price: 120K PHP.<br />
			Note: Price will be change base on USD currency rate
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="prod" style="width: 600px; background-color: #fff;">
		<div style="width: 150px; float: left;">
		<a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'><img src='<?= $this->basePath('samples/web-designs/design-five/images/thumb_5.jpg'); ?>' border='0' id='image_hover' /></a> 		<!--image-->
		</div>
		
		<div style="width: 449px; float: right; border-left: 1px solid #ccc; font-size: .8em;">
			<div style="background: #ddd; padding: 5px;">
			<span>Set of bracelet, earing and ring</span><br />																		<!--title-->	
			<span style='color: #999; font-size: .7em; font-style: italic; padding-bottom: 5px;'>Macrh 18, 2011</span>
			</div>
			<div style="padding: 5px;">																							<!--description-->
			With custom flower designed set, planted with diamonds, worth 150K PHP.<br /><br />

			Note: Price will be change base us US dollar currency.
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="prod" style="width: 600px; background-color: #fff;">
		<div style="width: 150px; float: left;">
		<a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'><img src='<?= $this->basePath('samples/web-designs/design-five/images/thumb_7.jpg'); ?>' border='0' id='image_hover' /></a> 		<!--image-->
		</div>
		
		<div style="width: 449px; float: right; border-left: 1px solid #ccc; font-size: .8em;">
			<div style="background: #ddd; padding: 5px;">
			<span>Neckless with pendant keys</span><br />																		<!--title-->	
			<span style='color: #999; font-size: .7em; font-style: italic; padding-bottom: 5px;'>Macrh 18, 2011</span>
			</div>
			<div style="padding: 5px;">																							<!--description-->
			These jewelry items, was made custom. Price will depend on your custom design you would like.<br><br>
			Note: Prices will be change base on USD currency.
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="prod" style="width: 600px; background-color: #fff;">
		<div style="width: 150px; float: left;">
		<a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'><img src='<?= $this->basePath('samples/web-designs/design-five/images/thumb_6.jpg'); ?>' border='0' id='image_hover' /></a> 		<!--image-->
		</div>
		
		<div style="width: 449px; float: right; border-left: 1px solid #ccc; font-size: .8em;">
			<div style="background: #ddd; padding: 5px;">
			<span>Set of earing with ring</span><br />																		<!--title-->	
			<span style='color: #999; font-size: .7em; font-style: italic; padding-bottom: 5px;'>Macrh 18, 2011</span>
			</div>
			<div style="padding: 5px;">																							<!--description-->
			This set of white gold flowered jewelry worth, 50K PHP.<br /><br />

			Note: Price will change base on dollar currency.
			</div>
		</div>
		<div class="clear"></div>
	</div>

	
		<div id="pagi">
			<div>Pages:</div>
			<div style="font-weight: bold; color: blue;">
			1
			</div>
		</div>
	</div> <!-- end products div -->


	<div class="ams">

		<table width="100%" cellpadding="2px">
			<tr>
				<td bgcolor="#ffffff"><b>AMS JEWELRY COLLECTION</b></td>
			</tr>
			<tr>
				<td>
				Contact #: 1234567890<br />
				Address: Agoo, La Union, Phillipines
				</td>
			</tr>
		</table>
				<hr /><br />
		<table width="100%" cellpadding="2px">
			<tr>
				<td bgcolor="#ffffff"><b>Our Service</b></td>
			</tr>
			<tr>
				<td>
				We made custom made jewelry items.<br />
				We also repair jewelry and furnish gold items.
				</td>
			</tr>
		</table>
				<hr /><br />
		<table width="100%" cellpadding="2px">
			<tr>
				<td bgcolor="#ffffff"><b>Our Vision</b></td>
			</tr>
			<tr>
				<td>
				To give our clients 100% satisfaction on every products we design. Reasonable prices, we also accept short-term payment on most our products.<br />
				We give our customer happy all the time and never regret in having business with us
				</td>
			</tr>
		</table>
				<hr /><br />
		<table width="100%" cellpadding="2px">
			<tr>
				<td bgcolor="#ffffff"><b>For sale:</b></td>
			</tr>
			<tr>
				<td>
				Luxury Mercedes Benz<br />
				Model 500L<br />
				Color: white.<br />
				Good for bridal car and daily or social trip
				</td>
			</tr>
		</table>
				<hr /><br />
		<table width="100%" cellpadding="2px">
			<tr>
				<td bgcolor="#ffffff"><b>For lease:</b></td>
			</tr>
			<tr>
				<td>
				House and Lot:<br />
				Address: 123st. Zone Dimasapulan, Baguio, City
				</td>
			</tr>
		</table>
		<hr /><br />

	</div>
	<div class="clear"></div>
	
	</div>
</div>

<div id="footer_holder">
    <div id="footer">
    Copyright &copy; AMS Jewelry Collection 2011. All Rights Reserved | <a href="http://moli-dev.comlu.com/" target="_blank">DESIGN BY MOLI S.</a>
    </div>
</div>
</body>