<body>
<?php $mylogo_url = $this->basePath('samples/web-designs/images/mylogo.jpg'); ?>
<!-- start header -->
<div id="header">
  <div id="logo">
   <div style="padding-top: 50px;">
   <a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>
       <img src="<?php echo $this->basePath('samples/web-designs/design-two/images/logo.png'); ?>" width="300" height="90" border="0"/>
   </a>
   </div>
 
  </div>
  <div id="menu-bg">
  <div id="menu">
    <ul id="main">
      <li class="current_page_item"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Homepage</a></li>
      <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Products</a></li>
      <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Services</a></li>
      <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>About Us</a></li>
      <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Contact Us</a></li>
    </ul>
    <ul id="feed">
      <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Comments</a></li>
    </ul>
  </div>
  </div>
</div>
<!-- end header -->
<div id="wrapper">
  <!-- start page -->
  <div id="page">
    <!-- start content -->
    <div id="content">
      <div style="padding-bottom: 20px;"><img src="images/img02.jpg" alt="" /></div>
      <div class="post">
        <h1 class="title"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Welcome to Our Website!</a></h1>
        <p class="byline">&nbsp;</p>
        <div class="entry">
          <p>Our Company is one of the top supplier of Home Furniture and Texture, and a leading Company in the Country.  One of the goal is to set all residence in the country to have a nice comportable standard of living with the help of our products and services. We will do all the works for our customers without any hasstles.</p>
          
          <p class="links"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design' class="more">Read Full Story</a> &nbsp;&nbsp;&nbsp;</p>
        </div>
      </div>
      <div class="post">
        <h2 class="title"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Head Office</a></h2>
        <p class="byline"><small>Posted on December 1st, 2010</small></p>
        <div class="entry">
          <p> Company expenses on the fourth quarter of the year may lead to undevastating delay on some weather condition on the country which also happenning on the whole world, because of global warnming, our services change slightly different than ever before. As part of the weather issue, the Company became more stronger than ever. Many of our suppliers and clients had ordered our products that helps every individuals to furnish and replenish their stocks on every major consumers.</p>
          <p class="links"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design' class="more">Read Full Story</a> &nbsp;&nbsp;&nbsp;</p>
        </div>
      </div>
      <div class="post">
        <h2 class="title"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Living Advice</a></h2>
        <p class="byline"><small>Posted on NOvember 21st</small></p>
        <div class="entry">
          <p>Thanks for The Healing Power of Coffee. Since most middle-aged Filipinos prefer coffee over tea and other drinks, we are truly grateful for the benefits of caffeine.</p>
          <p>I would love to be able to afford to taste all the mixed coffee drinks served at a well-known coffee shop here. When are you going to publish an article on 101 ways to serve coffee.</p>
          <p class="links"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design' class="more">Read Full Story</a> &nbsp;&nbsp;&nbsp;</p>
        </div>
      </div>
    </div>
    <!-- end content -->
    <!-- start sidebars -->
    <div id="sidebar1" class="sidebar">
      <ul>
        <li>
          <h2>Top Agents</h2>
          <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Albert Montano</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Casidy Dacanay</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Melchor Galvan Ventura</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Sigmond Yvan Fortes</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Arvin Patrimosa</a></li>
          </ul>
        </li>
        <li>
          <h2>Suppliers</h2>
          <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Paint Co.</a> on <br /><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Alex Panes</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>La Union Commercials</a> on <a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Jojo Molina</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>The Manila Group Inc.</a> on <a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Marlon James Javaier</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>James Uy Ltd.</a> on <br /><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Mona Em Sanchez</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Larazabal Home Products</a> on <a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Dominador Balagot</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Give me more shop</a> on <br /><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Marie Ann Torres</a></li>
          </ul>
        </li>
        <li>
          <h2>Categories</h2>
          <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Home Decoration</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Home Furniture</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Internal Designs</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Decor Paint</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Uratex Appliances</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Cemento Factory</a></li>
          </ul>
        </li>
        <li>
          <h2>Archives</h2>
          <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>September</a> (23)</li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>August</a> (31)</li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>July</a> (31)</li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>June</a> (30)</li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>May</a> (31)</li>
          </ul>
        </li>
      </ul>
    </div>
    <div id="sidebar2" class="sidebar">
      <ul>
        <li>
          <form id="searchform" method="get" action="#">
            <div>
              <input type="text" name="s" id="s" size="15" value="" />
              <br />
            </div>
          </form>
        </li>
        <li>
          <h2>Quality</h2>
          <p><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Top of the class brands and high quality products. Only here at our place where you can find a reasonable price where we can make your home a color and a design you want it to be. </a></p>
        </li>
        <li>
          <h2>Calendar</h2>
          <div id="calendar_wrap">
            <table width="100%" summary="Calendar">
              <caption>
              January 2011
              </caption>
              <thead>
                <tr>
                  <th abbr="Monday" scope="col" title="Monday">M</th>
                  <th abbr="Tuesday" scope="col" title="Tuesday">T</th>
                  <th abbr="Wednesday" scope="col" title="Wednesday">W</th>
                  <th abbr="Thursday" scope="col" title="Thursday">T</th>
                  <th abbr="Friday" scope="col" title="Friday">F</th>
                  <th abbr="Saturday" scope="col" title="Saturday">S</th>
                  <th abbr="Sunday" scope="col" title="Sunday">S</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <td abbr="September" colspan="3" id="prev"><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design' title="View posts for January 2011">&laquo; Jan</a></td>
                  <td class="pad">&nbsp;</td>
                  <td colspan="3" id="next">&nbsp;</td>
                </tr>
              </tfoot>
              <tbody>
                <tr>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td>&nbsp;</td>
                  <td id="today">&nbsp;</td>
                  <td>&nbsp;</td>
                  <td>1</td>
                  <td>2</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>4</td>
                  <td>5</td>
                  <td>6</td>
                  <td>7</td>
                  <td>8</td>
                  <td>9</td>
                </tr>
                <tr>
                  <td>10</td>
                  <td>11</td>
                  <td>12</td>
                  <td>13</td>
                  <td>14</td>
                  <td>15</td>
                  <td>16</td>
                </tr>
                <tr>
                  <td>17</td>
                  <td>18</td>
                  <td>19</td>
                  <td>20</td>
                  <td>21</td>
                  <td>22</td>
                  <td>23</td>
                </tr>
                <tr>
                  <td>24</td>
                  <td>25</td>
                  <td>26</td>
                  <td>27</td>
                  <td>28</td>
                  <td>29</td>
                  <td>30</td>
                </tr>
                <tr>
                	<td>31</td>
                  <td colspan="6">&nbsp;</td>
                </tr>
              </tbody>
            </table>
          </div>
        </li>
        <li>
          <h2>Branches</h2>
          <ul>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Ayala Ave, Makati City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Intramuros Manila</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Cubao Quezon City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Laguna Los Banos</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Batangas Lipa City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Zambales</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Bataan City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Tarlac City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Dagupan City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Baguio City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>San Fernando</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Laoag City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Cebu City</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Palawan</a></li>
            <li><a href="<?php echo $mylogo_url; ?>" rel='lightbox' title='moli&#39;s sample design'>Dominador</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- end sidebars -->
    <div style="clear: both;">&nbsp;</div>
  </div>
  <!-- end page -->
</div>
<div id="footer">
  <div id="footer-content">
    <p>&copy;2010 All Rights Reserved. &nbsp;&nbsp; <a href="http://www.moli.0fees.net/">Design by moli s.</a>.</p>
  </div>
</div>
</body>