<h2>Products</h2>
<div class="row col-md-8">
<table class="table table-condensed table-striped table-hover">
	<colgroup>
		<col width="5%" />
		<col width="40%" />
		<col width="40%" />
		<col width="5px" />
		<col width="5px" />
	<thead>
		<tr>
			<th>#</th>
			<th>Products</th>
			<th>Price</th>
			<th colspan="2" class="text-center">Action</th>
		</tr>
	</thead>
	<tbody>
		<tr data-ng-repeat="product in products | orderBy:'product'">
			<td>{{$index+1}}</td>
			<td>{{product.product}}</td>
			<td>{{product.price}}</td>	
			<td><a href="#/delete/product/{{product.id}}"><i class="btn glyphicon glyphicon-remove"><i></i></i></a></td>
			<td><a href="#/update/product/{{product.id}}"><i class="btn glyphicon glyphicon-pencil"><i></i></i></a></td>

		</tr>
	</tbody>
</table>
</div>
