<div class="container">
    <br>
	<div class="row">
		<div class="col-sm-2">
			<img src="<?php echo $this->basePath(); ?>/img/me2.jpg" class="img-circle img-thumbnail">
			<p style="padding-top:5px; color:#428BCA;" class="small">Romulo G. Soriano Jr.</p>
		
		</div>
		<div class="col-md-8">
		<h1>Web Developer</h1>
		<p><i class="glyphicon glyphicon-phone-alt size_18"></i> : +63 9165616800 / +63 9202109042</p>
		</div>
	</div>
	<div class="row">
	<hr>
		<h3>Skills Set</h3><br>
		<div class="col-md-12">
			<div class="col-md-3">
				<p><strong>Programming</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Php</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Javascript</p>
				<br>
				<p><strong>Database</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Mysql</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Posgre</p>
				<br>
				<p><strong>Web</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> XHTML, HTML4, HTML5</p>
				<p><i class=" glyphicon glyphicon-ok"></i> CSS2, CSS3</p>	
				<p><i class=" glyphicon glyphicon-ok"></i> XML</p>	
			</div>
			<div class="col-md-3">
				<p><strong>Framework</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Code Igniter</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Zend2</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Twitter Bootstrap3</p>
                                <p><i class=" glyphicon glyphicon-ok"></i> Jquery</p>
                                <p><i class=" glyphicon glyphicon-ok"></i> Backbone.js</p>
				<p><i class=" glyphicon glyphicon-ok"></i> AngularJS</p>
				<br>
				<p><strong>Graphics</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Adobe Photophop</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Adobe Illustratop</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Coreldraw</p>
				<p><i class=" glyphicon glyphicon-ok"></i> 3DMax</p>
			</div>
			<div class="col-md-3">
				<p><strong>OS</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Windows</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Linux</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Mac</p>
				<br>
				<p><strong>Version Control</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Git</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Mercurial</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Perforce</p>
				<br>
				<p><strong>Others</strong></p>
				<p><i class=" glyphicon glyphicon-ok"></i> Grunt.js</p>
				<p><i class=" glyphicon glyphicon-ok"></i> LESS - CSS</p>
				<p><i class=" glyphicon glyphicon-ok"></i> RequireJs</p>
				<p><i class=" glyphicon glyphicon-ok"></i> VMWare</p>
				<p><i class=" glyphicon glyphicon-ok"></i> Virtual Box</p>
				<br>
				
			</div>
		</div>
	</div>
</div>