<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
        <li data-slide-to="1" data-target="#myCarousel"></li>
        <li data-slide-to="2" data-target="#myCarousel"></li>
        <li data-slide-to="3" data-target="#myCarousel"></li>
        <li data-slide-to="4" data-target="#myCarousel"></li>
        <li data-slide-to="5" data-target="#myCarousel"></li>
    </ol>

    <div class="carousel-inner">

        <div class="item active">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic1.jpg" class="banner_img">
        </div>

        <div class="item">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic2.jpg" class="banner_img">
        </div>

        <div class="item">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic3.jpg" class="banner_img">
        </div>

        <div class="item">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic4.jpg" class="banner_img">
        </div>

        <div class="item">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic5.jpg" class="banner_img">
        </div>

        <div class="item">
            <img src="<?php echo $this->basePath(); ?>/img/banners/pic6.jpg" class="banner_img">
        </div>

    </div>

    <a data-slide="prev" href="#myCarousel" class="left carousel-control">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>

    <a data-slide="next" href="#myCarousel" class="right carousel-control">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
<div class="container">
    <h1 style="text-align:center">Bootstrap + AngularJS <small>= Awesome</small></h1><hr />

    <div class="col-md-6">
        <h2><small>PHP Developer</small></h2>
        <br />
        <p>
            I rewrited this site from Code Igniter to Zend Framework 2, maybe soon I will rewrite to ZF3 and use the Expressive and Middleware Interface.
            I did not put any third party plugins on this website, just a simple bootstrap to help me most of my html structures, and I want to be simple as possible
            and to focus more on my sample projects on <a href='<?php echo $this->basePath(); ?>main/samples'>Samples</a> page.
        </p>
        <p> I started my Web development career when I was working on Saudi Arabia and now currently in the Philippines and worked on different companies as a PHP Web Developer. </p>
        <p> I handled different kinds of projects on every Companies that I worked and have an extensive knowledge of web technologies including PHP, HTML, CSS, Javascript, AJAX etc., and experienced in common third-party APIs (google, facebook, etc).
            I also handled on Enterprise level development using Web Services like REST and SOAP. Framework like Code Igniter2, Zend2, BackboneJs, AngularJs, Bootstrap, etc. and automation and minification like GruntJs, LESS - CSS, RequireJs.</p>
        <p>
            I have an advance knowledge on different platforms like Windows, Linux or LAMP Environment and Repositories like, Mercurial, Git, etc. for version control system.
        </p>
        <p>	
            I can work as a Back-end and Front-end in web development, but I am more focus on Back-end development based on my experiences. I have my passion for best design and advance coding practices like Object Oriented Programming or OOP, 
            Design Patterns for large scale projects and also have a desire to develop new bold ideas.
        </p>
        <p>	I have some sample projects on the <a href='<?php echo $this->basePath(); ?>main/samples'>Samples</a> page and I have to add more projects soon.</p>

    </div>
    <div class="col-md-6">
        <h2><small>Just another day at work</small></h2>
        <img src="<?php echo $this->basePath(); ?>/img/piccollage.jpg" width="100%"/>
        <img src="<?php echo $this->basePath(); ?>/img/piccollage2.jpg" width="100%"/>
    </div>
</div>
<br /><br /><br />