<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Main\Module'                    => __DIR__ . '/Module.php',
    'Main\Controller\MainController' => __DIR__ . '/src/Main/Controller/MainController.php',
);
